#pragma once
#include <string_view>
#include <unordered_map>
#include <utility>

namespace Name::Space {
enum class ExampleEnum : int {
	INVALID_TOKEN,
	IDENTIFIER,
	SIGNED_LITERAL,
	UNSIGNED_LITERAL,
	FLOAT_LITERAL,
	DOUBLE_LITERAL,
	STRING_LITERAL,
	CHAR_LITERAL,
	BOOL_LITERAL,
	PLUS,
	PLUSPLUS,
	MINUS,
	MINUSMINUS,
	SLASH,
	STAR,
	MOD,
	ASSIGN,
	LPAREN,
	RPAREN,
	LBRACE,
	RBRACE,
	LBRACKET,
	RBRACKET,
	LESS,
	ARROW,
	GTR,
	LESSEQ,
	GTREQ,
	SEMI_COLON,
	COLON,
	ADDR,
	COMMA,
	DOT,
	KEYWORD_AND,
	KEYWORD_OR,
	KEYWORD_XOR,
	KEYWORD_NOT,
	KEYWORD_EQUALS,
	KEYWORD_NOT_EQUAL,
	KEYWORD_BITAND,
	KEYWORD_BITOR,
	KEYWORD_BITXOR,
	KEYWORD_BITNOT,
	KEYWORD_i8,
	KEYWORD_i16,
	KEYWORD_i32,
	KEYWORD_i64,
	KEYWORD_u8,
	KEYWORD_u16,
	KEYWORD_u32,
	KEYWORD_u64,
	KEYWORD_f32,
	KEYWORD_f64,
	KEYWORD_CHAR,
	KEYWORD_STRING,
	KEYWORD_BOOL,
	KEYWORD_DEVOID,
	KEYWORD_RAW,
	KEYWORD_UNIQUE,
	KEYWORD_VAGUE,
	KEYWORD_MUT,
	KEYWORD_IF,
	KEYWORD_ELSE,
	KEYWORD_FOR,
	KEYWORD_WHILE,
	KEYWORD_RETURN,
	KEYWORD_SWITCH,
	KEYWORD_CASE,
	KEYWORD_DEFAULT,
	KEYWORD_CAST,
	KEYWORD_GLOBAL,
	KEYWORD_NULL,
	KEYWORD_JUNK,
	KEYWORD_FN,
	KEYWORD_STRUCT,
	KEYWORD_PUB,
	KEYWORD_IMPORT,
	DUNDER_CEXTERN,
	DUNDER_VA,
};
inline const std::unordered_map<std::string_view, ExampleEnum> stringToExampleEnum{
	{"INVALID_TOKEN", ExampleEnum::INVALID_TOKEN}, {"IDENTIFIER", ExampleEnum::IDENTIFIER}, {"SIGNED_LITERAL", ExampleEnum::SIGNED_LITERAL}, 
	{"UNSIGNED_LITERAL", ExampleEnum::UNSIGNED_LITERAL}, {"FLOAT_LITERAL", ExampleEnum::FLOAT_LITERAL}, 
	{"DOUBLE_LITERAL", ExampleEnum::DOUBLE_LITERAL}, {"STRING_LITERAL", ExampleEnum::STRING_LITERAL}, 
	{"CHAR_LITERAL", ExampleEnum::CHAR_LITERAL}, {"BOOL_LITERAL", ExampleEnum::BOOL_LITERAL}, 
	{"+", ExampleEnum::PLUS}, {"++", ExampleEnum::PLUSPLUS}, 
	{"--", ExampleEnum::MINUS}, {"---", ExampleEnum::MINUSMINUS}, 
	{"/", ExampleEnum::SLASH}, {"*", ExampleEnum::STAR}, 
	{"%", ExampleEnum::MOD}, {"=", ExampleEnum::ASSIGN}, 
	{"(", ExampleEnum::LPAREN}, {")", ExampleEnum::RPAREN}, 
	{"{", ExampleEnum::LBRACE}, {"}", ExampleEnum::RBRACE}, 
	{"[", ExampleEnum::LBRACKET}, {"]", ExampleEnum::RBRACKET}, 
	{"<", ExampleEnum::LESS}, {"-->", ExampleEnum::ARROW}, 
	{">", ExampleEnum::GTR}, {"<=", ExampleEnum::LESSEQ}, 
	{">=", ExampleEnum::GTREQ}, {";", ExampleEnum::SEMI_COLON}, 
	{":", ExampleEnum::COLON}, {"@", ExampleEnum::ADDR}, 
	{",", ExampleEnum::COMMA}, {".", ExampleEnum::DOT}, 
	{"and", ExampleEnum::KEYWORD_AND}, {"or", ExampleEnum::KEYWORD_OR}, 
	{"xor", ExampleEnum::KEYWORD_XOR}, {"not", ExampleEnum::KEYWORD_NOT}, 
	{"eq", ExampleEnum::KEYWORD_EQUALS}, {"not_eq", ExampleEnum::KEYWORD_NOT_EQUAL}, 
	{"bitand", ExampleEnum::KEYWORD_BITAND}, {"bitor", ExampleEnum::KEYWORD_BITOR}, 
	{"bitxor", ExampleEnum::KEYWORD_BITXOR}, {"bitnot", ExampleEnum::KEYWORD_BITNOT}, 
	{"i8", ExampleEnum::KEYWORD_i8}, {"i16", ExampleEnum::KEYWORD_i16}, 
	{"i32", ExampleEnum::KEYWORD_i32}, {"i64", ExampleEnum::KEYWORD_i64}, 
	{"u8", ExampleEnum::KEYWORD_u8}, {"u16", ExampleEnum::KEYWORD_u16}, 
	{"u32", ExampleEnum::KEYWORD_u32}, {"u64", ExampleEnum::KEYWORD_u64}, 
	{"f32", ExampleEnum::KEYWORD_f32}, {"f64", ExampleEnum::KEYWORD_f64}, 
	{"char", ExampleEnum::KEYWORD_CHAR}, {"string", ExampleEnum::KEYWORD_STRING}, 
	{"bool", ExampleEnum::KEYWORD_BOOL}, {"-", ExampleEnum::KEYWORD_DEVOID}, 
	{"raw", ExampleEnum::KEYWORD_RAW}, {"unique", ExampleEnum::KEYWORD_UNIQUE}, 
	{"vague", ExampleEnum::KEYWORD_VAGUE}, {"mut", ExampleEnum::KEYWORD_MUT}, 
	{"if", ExampleEnum::KEYWORD_IF}, {"else", ExampleEnum::KEYWORD_ELSE}, 
	{"for", ExampleEnum::KEYWORD_FOR}, {"while", ExampleEnum::KEYWORD_WHILE}, 
	{"return", ExampleEnum::KEYWORD_RETURN}, {"switch", ExampleEnum::KEYWORD_SWITCH}, 
	{"case", ExampleEnum::KEYWORD_CASE}, {"default", ExampleEnum::KEYWORD_DEFAULT}, 
	{"cast", ExampleEnum::KEYWORD_CAST}, {"global", ExampleEnum::KEYWORD_GLOBAL}, 
	{"null", ExampleEnum::KEYWORD_NULL}, {"junk", ExampleEnum::KEYWORD_JUNK}, 
	{"fn", ExampleEnum::KEYWORD_FN}, {"struct", ExampleEnum::KEYWORD_STRUCT}, 
	{"pub", ExampleEnum::KEYWORD_PUB}, {"import", ExampleEnum::KEYWORD_IMPORT}, 
	{"__C", ExampleEnum::DUNDER_CEXTERN}, {"__va", ExampleEnum::DUNDER_VA}, 
	
};

constexpr std::string_view ExampleEnumToString(ExampleEnum e) {
	static constexpr std::string_view toString[] = {
	"INVALID_TOKEN","IDENTIFIER","SIGNED_LITERAL",
	"UNSIGNED_LITERAL","FLOAT_LITERAL",
	"DOUBLE_LITERAL","STRING_LITERAL",
	"CHAR_LITERAL","BOOL_LITERAL",
	"+","++",
	"--","---",
	"/","*",
	"%","=",
	"(",")",
	"{","}",
	"[","]",
	"<","-->",
	">","<=",
	">=",";",
	":","@",
	",",".",
	"and","or",
	"xor","not",
	"eq","not_eq",
	"bitand","bitor",
	"bitxor","bitnot",
	"i8","i16",
	"i32","i64",
	"u8","u16",
	"u32","u64",
	"f32","f64",
	"char","string",
	"bool","-",
	"raw","unique",
	"vague","mut",
	"if","else",
	"for","while",
	"return","switch",
	"case","default",
	"cast","global",
	"null","junk",
	"fn","struct",
	"pub","import",
	"__C","__va",
	
};
	return toString[std::to_underlying(e)];
}
constexpr bool isCategoryLITERALS(ExampleEnum e) { return std::to_underlying(e) >= 2 && std::to_underlying(e) < 9; }
constexpr bool isCategorySYMBOLS(ExampleEnum e) { return std::to_underlying(e) >= 9 && std::to_underlying(e) < 33; }
constexpr bool isCategoryKEYWORDS(ExampleEnum e) { return std::to_underlying(e) >= 33 && std::to_underlying(e) < 77; }
constexpr bool isCategoryBITWISE(ExampleEnum e) { return std::to_underlying(e) >= 33 && std::to_underlying(e) < 43; }
constexpr bool isCategoryPRIMITIVES(ExampleEnum e) { return std::to_underlying(e) >= 43 && std::to_underlying(e) < 60; }
constexpr bool isCategoryPOINTERS(ExampleEnum e) { return std::to_underlying(e) >= 57 && std::to_underlying(e) < 60; }
constexpr bool isCategoryTYPE_MODIFIERS(ExampleEnum e) { return std::to_underlying(e) >= 60 && std::to_underlying(e) < 61; }
constexpr bool isCategoryCONTROL_FLOW(ExampleEnum e) { return std::to_underlying(e) >= 61 && std::to_underlying(e) < 69; }
constexpr bool isCategoryCAST(ExampleEnum e) { return std::to_underlying(e) >= 69 && std::to_underlying(e) < 70; }
constexpr bool isCategoryMODULE(ExampleEnum e) { return std::to_underlying(e) >= 75 && std::to_underlying(e) < 77; }
constexpr bool isCategoryDUNDER(ExampleEnum e) { return std::to_underlying(e) >= 77 && std::to_underlying(e) < 79; }

}; //namespace Name::Space